### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by eboye** [rastasheep/google-plus-share#2]
![not_working](https://cloud.githubusercontent.com/assets/624357/23343876/1465ea02-fc73-11e6-949f-bfa729d7b157.gif)
It kinda opens and closes the popup ...

**Comment by rastasheep** [comment]
Sorry for that. Can you check latest release (v0.0.2) i've discovered right way to use Chrome API.

**Comment by eboye** [comment]
Yup, working like a charm ;) Thanks ...
